- name: backend
  hosts: backend
  become: yes
  tasks:
  - name: disable nodejs package
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: add expense user
    ansible.builtin.user:
      name: expense
  
  - name: create a /app directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the application code to created repository
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  
  - name: unarchive the file that is already in the remote mession
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes